name: Deploy to S3
on:
  push:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync \
          --region ap-northeast-1 \
          --exact-timestamps \
          --exclude '.git/*' \
          --exclude '.github/*' \
          --exclude .gitignore \
          --exclude '*.css' \
          --exclude 'image/*' \
          --exclude '*.rss' \
          --exclude 'redirect/*' \
          --delete \
          --metadata-directive REPLACE \
          --cache-control "max-age=86400, no-cache, public" \
          ./ s3://tenjuu-net-web/

          aws s3 sync \
          --region ap-northeast-1 \
          --exact-timestamps \
          --exclude '.git/*' \
          --exclude '.github/*' \
          --exclude .gitignore \
          --exclude '*.css' \
          --exclude 'image/*' \
          --exclude '*.rss' \
          --exclude 'redirect/*' \
          --delete \
          --metadata-directive REPLACE \
          --cache-control "max-age=86400, no-cache, public" \
          --metadata "Website-Redirect-Location=/index.html" \
          --metadata "HttpRedirectCode=302" \
          ./redirect/ s3://tenjuu-net-web/
